-- User Schema
CREATE TABLE users (email VARCHAR(255) NOT NULL PRIMARY KEY, password VARCHAR(255) NOT NULL, registered_type VARCHAR(20) NOT NULL);

-- Book Schema
CREATE TABLE books (title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, ISBN VARCHAR(20) NOT NULL PRIMARY KEY, price DECIMAL(10, 2) NOT NULL, quantity INT NOT NULL);
